TesteNovaVida/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TesteNovaVida.Models
{
    public class Professor

    {
        [Display(Name = "IdProfessor")]
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int IdProfessor {get; set;}
        
        [Display(Name="NomeProfessor")]
        [Required(ErrorMessage = "Preenchimento obrigatório !")]
        [DataType(DataType.Text, ErrorMessage = "O campo nome está Vazio")]
        public string NomeProfessor {get; set;}  

       
        [ForeignKey("IdProfessor")]
        public List<Aluno>? Alunos { get; set; }

    }
}

TesteNovaVida/Controllers/AlunoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteNovaVida.Data;
using TesteNovaVida.Models;

namespace TesteNovaVida.Controllers
{
    public class AlunoesController : Controller
    {
        private readonly TesteNovaVidaContext _context;

        public AlunoesController(TesteNovaVidaContext context)
        {
            _context = context;
        }

        // GET: Alunoes
        public async Task<IActionResult> Index()
        {
            var TesteNovaVidaContext = _context.Aluno.Include(a => a.Professor);
            return View(await TesteNovaVidaContext.ToListAsync());
        }
          

        public IActionResult Create(string? nome)
        {
            if (nome != null)
                ViewData["nomeProf"] = nome;

            ViewData["IdProfessor"] = new SelectList(_context.Professor, "IdProfessor", "NomeProfessor");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAluno,IdProfessor,NomeAluno,ValorMensalidade,DataVencimento")] Aluno aluno , string? nome)
        {
            if (ModelState.IsValid)
            {                
                _context.Add(aluno);
                await _context.SaveChangesAsync();
               
                if (nome == null) 
                     return RedirectToAction(nameof(Index));
                else
                     return RedirectToAction("ListarAlunosProfessor", "Professors", new { id = aluno.IdProfessor, nome = nome });

            }
            ViewData["IdProfessor"] = new SelectList(_context.Professor, "IdProfessor", "NomeProfessor", aluno.IdProfessor);
            return View(aluno);
        }

        // GET: Alunoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Aluno.FindAsync(id);
            if (aluno == null)
            {
                return NotFound();
            }
            ViewData["IdProfessor"] = new SelectList(_context.Professor, "IdProfessor", "NomeProfessor", aluno.IdProfessor);
            return View(aluno);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAluno,IdProfessor,NomeAluno,ValorMensalidade,DataVencimento")] Aluno aluno, string? nome)
        {
            if (id != aluno.IdAluno)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aluno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunoExists(aluno.IdAluno))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                if (nome == null) 
                     return RedirectToAction(nameof(Index));
                else
                     return RedirectToAction("ListarAlunosProfessor", "Professors", new { id = aluno.IdProfessor, nome = nome });
              
            }

            ViewData["IdProfessor"] = new SelectList(_context.Professor, "IdProfessor", "NomeProfessor", aluno.IdProfessor);

            return View(aluno);


        }

        // GET: Alunoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Aluno
                .Include(a => a.Professor)
                .FirstOrDefaultAsync(m => m.IdAluno == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // POST: Alunoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aluno = await _context.Aluno.FindAsync(id);
            if (aluno != null)
            {
                _context.Aluno.Remove(aluno);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunoExists(int id)
        {
            return _context.Aluno.Any(e => e.IdAluno == id);
        }


        [HttpPost, ActionName("DeleteDirect")]
        public async Task DeleteDirect(int id)
        {
            var aluno = await _context.Aluno.FindAsync(id);
            if (aluno != null)
            {
                _context.Aluno.Remove(aluno);
            }

            await _context.SaveChangesAsync();
        }
    }
}

TesteNovaVida/Controllers/ImportController.cs
using TesteNovaVida.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Mvc;
using TesteNovaVida.Data;
using System.Text;


namespace TesteNovaVida.Controllers
{
    public class ImportController : Controller
    {
        private readonly TesteNovaVidaContext _context;
        private IHostingEnvironment Environment;        
        private readonly IConfiguration _configuration;

        public ImportController(TesteNovaVidaContext context, IHostingEnvironment _environment, IConfiguration configuration)
        {
             _context = context;
             Environment = _environment;
             _configuration = configuration;
        }

        // GET: Home
        public ActionResult Index()
        {
            return View(new List<Aluno>());
        }

        [HttpPost]
        public  IActionResult Index(string id, string nome, IFormFile postedFile)
        {
            //Trata e Verificação configuração do intervalo para uma nova importação

            TimeZoneInfo Standard_Time = TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time");
            DateTime dataHoraLocal = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, Standard_Time);
            UltimaImportacao primeiraImportacao = new UltimaImportacao();

            UltimaImportacao ultimaDataHoraGravada = _context.UltimaImportacao.SingleOrDefault();
            if (ultimaDataHoraGravada != null)
            {               
                DateTime dataTermino = ultimaDataHoraGravada.DataHora.AddMinutes(_configuration.GetValue<int>("IntervaloMinutosNovaImportacao"));
                TimeSpan tempoRestante = dataTermino - dataHoraLocal;

                if (tempoRestante.Minutes > 0) //Caso não tenha expirado o limite de minutos para uma nova importação
                {
                    ViewData["Message"] = "Importação Negada! Ainda não expirou o tempo limite permitido para que possa fazer uma nova importação, aguarde: #" + tempoRestante.Minutes.ToString() + " minutos" + "#" + StatusCodes.Status403Forbidden + "#" + nome;
                    return View();
                }
                else //Caso o limite já tenha sido expirado grava a nova data e hora desta importação (Update)
                { 
                    ultimaDataHoraGravada.DataHora = dataHoraLocal;
                    _context.UltimaImportacao.Update(ultimaDataHoraGravada);
                    _context.SaveChanges();
                }
            }
            else //Primeira Importação faz o insert (apenas uma linha tabela)
            {
                primeiraImportacao.DataHora = dataHoraLocal;                
                _context.UltimaImportacao.Add(primeiraImportacao);
                _context.SaveChanges();
            }
        
            //Importação
            List<Aluno> alunos = new List<Aluno>();

            string filePath = string.Empty;
            if (postedFile != null)
            {
                string wwwPath = this.Environment.WebRootPath;
                string contentPath = this.Environment.ContentRootPath;

                string path = Path.Combine(this.Environment.WebRootPath, "Uploads");
                string fileName = Path.GetFileName(postedFile.FileName);
                filePath = path + "\\" + fileName;
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    stream.Dispose();

                    //Read the contents of CSV file.
                    string csvData = System.IO.File.ReadAllText(filePath,Encoding.Latin1);

                    //Execute a loop over the rows.
                    foreach (string row in csvData.Split('\n'))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            Aluno aluno = new Aluno();
                            aluno.IdProfessor = Convert.ToInt32(id);
                            aluno.NomeAluno = row.Split(',')[0];
                            aluno.ValorMensalidade = Convert.ToDecimal(row.Split(',')[1].Replace(".", ","));
                            aluno.DataVencimento = Convert.ToDateTime(row.Split(',')[2]);

                            alunos.Add(aluno);

                            _context.Add(aluno);
                            _context.SaveChanges();
                        }
                    }
                }

            }

         
            return RedirectToAction("ListarAlunosProfessor", "Professors", new { id = id, nome = nome, import = "s", total = alunos.Count.ToString() });
        }

    }
}

TesteNovaVida/Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Humanizer;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;
using TesteNovaVida.Data;
using TesteNovaVida.Models;


namespace TesteNovaVida.Controllers
{
    public class ProfessorsController : Controller
    {
        private readonly TesteNovaVidaContext _context;

        public ProfessorsController(TesteNovaVidaContext context)
        {
            _context = context;
        }

        // GET: Professors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Professor.ToListAsync());
        }

        // GET: Professors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professor
                .FirstOrDefaultAsync(m => m.IdProfessor == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProfessor,NomeProfessor")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        // GET: Professors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professor.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }
            return View(professor);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProfessor,NomeProfessor")] Professor professor)
        {
            if (id != professor.IdProfessor)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.IdProfessor))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = await _context.Professor
                .FirstOrDefaultAsync(m => m.IdProfessor == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var professor = await _context.Professor.FindAsync(id);
            if (professor != null)
            {
                _context.Professor.Remove(professor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessorExists(int id)
        {
            return _context.Professor.Any(e => e.IdProfessor == id);
        }


        public async Task<IActionResult> ListarAlunosProfessor(int? id, string? nome)
        {
            if (id == null)
            {
                return NotFound();
            }

            IEnumerable<object> nomeRet = null;

            List<Aluno> aluno =  _context.Aluno
                .Include(a => a.Professor)
               .Where(m => m.IdProfessor == id)
                .ToListAsync().Result;

            if (aluno == null)
            {
                return NotFound();
            }
         

            return View(aluno);
        }


        [HttpPost, ActionName("DeleteDirect")]
        public async Task DeleteDirect(int id)
        {

            if (ModelState.IsValid)
            {
                var alunos = _context.Aluno.Where(c => c.IdProfessor == id).ToList();
                foreach (var x in alunos)
                {
                    var com = x;
                    _context.Aluno.Remove(com);
                }

                await _context.SaveChangesAsync();

                var profesor = await _context.Professor.FindAsync(id);
                _context.Professor.Remove(profesor);

                await _context.SaveChangesAsync();
            }
            else
            {
                BadRequest(ModelState);
            }
            
        }
    }
}

TesteNovaVida/Views/Professors/Create.cshtml
@model TesteNovaVida.Models.Professor

@{
    ViewData["Title"] = "Create";
}

<h4 class="mt-2 mb-0">Incluir Professor</h4>
<hr class="mt-0" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeProfessor" class="control-label"> Nome do professor</label>
                <input asp-for="NomeProfessor" class="form-control" maxlength="100" />
                <span asp-validation-for="NomeProfessor" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Incluir" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<hr />
<button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Index", "Professors")'">Listar professores</button>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteNovaVida/Views/Professors/Edit.cshtml
@model TesteNovaVida.Models.Professor

@{
    ViewData["Title"] = "Alterar";
}

<h4 class="mb-0">Alterar Professor</h4>
<hr class="mt-0" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdProfessor" />
            <div class="form-group">
                <label asp-for="NomeProfessor" class="control-label">Nome do Professor</label>
                <input asp-for="NomeProfessor" class="form-control" maxlength="100" />
                <span asp-validation-for="NomeProfessor" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <input type="submit" value="Alterar" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<br />

<hr />
<button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Index", "Professors")'">Listar professores</button>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TesteNovaVida/Views/Professors/Index.cshtml
@model IEnumerable<TesteNovaVida.Models.Professor>

@{
    ViewData["Title"] = "Professores";
}

<h2>Professores</h2>
<hr />
<br />

<span class="ml-1">Total de Professores: <b>@Model.Count().ToString()</b></span>
<hr />
<div style="max-height: 400px; overflow-x: auto">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nome do professor
                </th>
                <th>
                    Ações
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeProfessor)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdProfessor" class="text-decoration-none">
                        <input class="btn btn-sm btn-outline-success mr-2" value="Alterar" style="width: 80px"/>
                    </a>
                    <a href='#' class="btnExcluir text-decoration-none" name="@item.IdProfessor">
                        <input class="btn btn-sm btn-outline-danger" value="Excluir" style="width: 80px" />
                    </a>
                        <a asp-action="ListarAlunosProfessor" asp-route-id="@item.IdProfessor" asp-route-nome="@item.NomeProfessor" class="text-decoration-none">
                        <input class="btn btn-sm btn-outline-secondary" value="Listar seus alunos" style="width: 150px" />
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<br />

<hr />
<div class="d-inline-block">
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Professors")'">Incluir professor</button>
    <button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Index", "Alunoes")'">Listar todos os alunos</button>
</div>


<script src="~/js/jquery.js"></script>
<script type="text/javascript">

    $(".table").on("click", ".btnExcluir", deleteRow);

    function deleteRow() {

        Swal.fire({
            title: "Confirmação",
            text: "Deseja excluir este professor e todos os alunos que já foram associados a ele?",
            icon: "warning",
            showCancelButton: true,
            buttonsStyling: false,
            confirmButtonText: "Sim, Excluir!",
            cancelButtonText: "Não, cancelar!",
            customClass: {
                confirmButton: 'btn btn-danger',
                cancelButton: 'btn btn-outline-secondary'
            }
        }).then((result) => {
            if (result.isConfirmed) {
                var id  = $(this).attr("name");
                Delete(id);

                var par = $(this).parent().parent();
                par.remove();
            }
            else {
                return false;
            }
        });
    };


    function Delete(id) {

        $.post({
            url: '/Professors/DeleteDirect/' + id,
            success: function (result, status, xhr) {
               msgAlunoExcluido();
            },
        });

    }

    function msgAlunoExcluido() {
        const Toast = Swal.mixin({
            toast: true,
            position: "center-center",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });
        Toast.fire({
            title: "O professor e todos os seus respectivos alunos foram <b style='color:red'>excluídos</b>!",
            icon: "danger"
        }).then(function () {
            return true;

        });
    }

</script>

TesteNovaVida/Views/Professors/ListarAlunosProfessor.cshtml
@using System.Globalization
@model IEnumerable<TesteNovaVida.Models.Aluno>

@if (Model.Count() > 0)
{
    ViewData["Title"] = "Alunos do professor";
}

<h2>Alunos do professor: <b style="color: blue">@Context.Request.Query["nome"]</b></h2>
<hr />

@if (@Context.Request.Query["import"].ToString() == "s")
{
    <div class="alert alert-success alert-with-icon" role="alert">
        <div class="alert-icon-box" style="display: inline-block; float: left; width: 40px; position: relative;">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check">
                <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
        </div>
        Foram importados <b>@Context.Request.Query["total"].ToString()</b> novos alunos e associados ao professor: <b>@Context.Request.Query["nome"].ToString()</b>
    </div>
    <hr />
}

@if (Model.Count() > 0)
{
    <span class="ml-1">Total de Alunos: <b>@Model.Count().ToString()</b></span>
    <hr />
    <div style="max-height: 400px; overflow-x: auto">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Nome do aluno
                    </th>
                    <th>
                        Valor da mensalidade
                    </th>
                    <th>
                        Data de vencimento
                    </th>
                    <th>
                        Ações
                    </th>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NomeAluno)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ValorMensalidade)
                        </td>
                        <td>
                            @Convert.ToDateTime(item.DataVencimento).ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            <a asp-controller="Alunoes" asp-action="Edit" asp-route-id="@item.IdAluno" asp-route-idprof="@item.IdProfessor"  asp-route-nome="@Context.Request.Query["nome"]" class="text-decoration-none">
                                <input class="btn btn-sm btn-outline-success mr-2" value="Alterar" style="width: 80px" />
                            </a> 
                            <a href='#' class="btnExcluir text-decoration-none" name="@item.IdAluno">
                                <input class="btn btn-sm btn-outline-danger" value="Excluir" style="width: 80px" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

@if (Model.Count() == 0)
{
    <div class="alert alert-warning alert-with-icon" role="alert">
        <div class="alert-icon-box" style="display: inline-block; float: left; width: 40px; position: relative;">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock alert-icon">
                <circle cx="12" cy="12" r="10"></circle>
                <polyline points="12 6 12 12 16 14"></polyline>
            </svg>
        </div>
        Nenhum aluno foi incluido para este professor ainda!
    </div>
}
<br />

<hr />
<div class="d-inline-block">
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Alunoes",  new {id = @Context.Request.RouteValues["id"], nome = @Context.Request.Query["nome"] })'">Incluir aluno</button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Import",  new { id = @Context.Request.RouteValues["id"], nome = @Context.Request.Query["nome"] })'">Importar Alunos</button>
    <button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Index", "Professors")'">Listar professores</button>
</div>


<script src="~/js/jquery.js"></script>

<script type="text/javascript">

    $(".table").on("click", ".btnExcluir", deleteRow);

    function deleteRow() {

        Swal.fire({
            title: "Confirmação",
            text: "Deseja excluir este aluno?",
            icon: "warning",
            showCancelButton: true,
            buttonsStyling: false,
            confirmButtonText: "Sim, Excluir!",
            cancelButtonText: "Não, cancelar!",            
            customClass: {
                confirmButton: 'btn btn-danger',
                cancelButton: 'btn btn-outline-secondary'
            }
        }).then((result) => {
            if (result.isConfirmed) {
                var id  = $(this).attr("name");
                Delete(id);

                var par = $(this).parent().parent();
                par.remove();
            }
            else {
                return false;
            }
        });
    };


    function Delete(id) {

        $.post({
            url: '/Alunoes/DeleteDirect/' + id,
            success: function (result, status, xhr) {
               msgAlunoExcluido();
            },
        });

    }

    function msgAlunoExcluido() {
        const Toast = Swal.mixin({
            toast: true,
            position: "center-center",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });
        Toast.fire({
            title: "O aluno foi <b style='color:red'>excluído</b>!",
            icon: "danger"
        }).then(function () {
            return true;

        });
    }

</script>